networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64

volumes:
  wgeasy-config:
    external: true

#secrets:

services:
  wgeasy:
    image: ghcr.io/wg-easy/wg-easy@sha256:5f26407fd2ede54df76d63304ef184576a6c1bb73f934a58a11abdd852fab549
    pull_policy: ${pull_policy}
    container_name: ${wireguard_container_name}
    restart: ${restart}
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    ports:
      - "${wireguard_port_51822}:51822/udp"
      - "${wireguard_port_51821}:51821/tcp"
    environment:    
      - TZ=${timezone}
      - WG_HOST=wg.${CADDY_PUBLIC_DOMAIN}
      - WG_PORT=51822
      - WG_DEFAULT_DNS=10.10.10.1
    volumes:
      - wgeasy-config:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

