---
include:
  - ../components/caddy_network.yaml

#networks:

volumes:
  gluetun-config:
    external: true
  qbittorrent-config:
    external: true
  sabnzbd-config:
    external: true
  prowlarr-config:
    external: true
  jellyseerr-config:
    external: true
  radarr-config:
    external: true
  sonarr-config:
    external: true
  sonarr2-config:
    external: true
  lidarr-config:
    external: true
  notifiarr-config:
    external: true

  media_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/downloads"
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"
  media_music:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/music"
  media_anime:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/anime"

#secrets:

services:
  gluetunmediarr:
    image: qmcgaw/gluetun:latest@sha256:d0afe1e24597f8a17a675291b0c581478e4795b25016837b7304c5e49359af52
    pull_policy: ${pull_policy}
    container_name: ${gluetunmediarr_container_name}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.200
    ports:
      - ${qbittorrent_port_ui}:${qbittorrent_port_ui}
      - ${sabnzbd_port_ui}:${sabnzbd_port_ui}
      - ${flaresolverr_port}:${flaresolverr_port}
      - ${prowlarr_port_ui}:${prowlarr_port_ui}
      - ${jellyseerr_port_ui}:${jellyseerr_port_ui}
      - ${radarr_port_ui}:${radarr_port_ui}
      - ${sonarr_port_ui}:${sonarr_port_ui}
      - ${lidarr_port_ui}:${lidarr_port_ui}
      - ${notifiarr_port_ui}:${notifiarr_port_ui}
      - ${sonarr_port_ui}:${sonarr_port_ui}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - GLUETUN_HTTP_CONTROL_SERVER_ENABLE=on
      #- WIREGUARD_ENDPOINT_IP=${MEDIARR_WG_ENDPOINT_IP}
      #- WIREGUARD_ENDPOINT_PORT=${MEDIARR_WG_ENDPOINT_PORT}
      #- WIREGUARD_PUBLIC_KEY=${MEDIARR_WG_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${MEDIARR_WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${MEDIARR_WG_ADDRESSES}
      - SERVER_HOSTNAMES=${MEDIARR_WG_SERVER_HOSTNAME}
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${qbittorrent_port_ui}/api/v2/app/setPreferences 2>&1'
      - DOT=on
      - DOT_PROVIDERS=cloudflare,google,quad9
      - DOT_CACHING=on
      - BLOCK_MALICIOUS=off
      - BLOCK_ADS=off
      - BLOCK_SURVEILLANCE=off
      - DNS_KEEP_NAMESERVER=off
      - DNS_ADDRESS=127.0.0.1
    volumes:
      - gluetun-config:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:a5b277bd1cb098dcba6215ab03ada24c28101ac16022e0e6c1ffed40743d4448
    pull_policy: ${pull_policy}
    container_name: ${qbittorrent_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=${qbittorrent_port_ui}
    volumes:
      - qbittorrent-config:/config
      - media_downloads/torrents:/media_downloads/torrents

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest@sha256:6e6e7abf7a87436ffccd7df41e64a28df9c530e2be5467339a3f5f0518922b49
    pull_policy: ${pull_policy}
    container_name: ${sabnzbd_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - sabnzbd-config:/config
      - media_downloads/usenet:/media_downloads/usenet

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:4f4e5f759aa3a9a64305e99188ea1db1ec2944a5e7d290d2b089af5f2f6f48e4
    pull_policy: ${pull_policy}
    container_name: ${flaresolverr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest@sha256:643220338204525524db787ff38a607261597f49d1f550694acdb3e908e2b43e
    pull_policy: ${pull_policy}
    container_name: ${prowlarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - flaresolverr
      - qbittorrent
      - sabnzbd
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - prowlarr-config:/config

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest@sha256:9cc9e9ee6cd5cf5a23feb45c37742ba34cfd6314d81d259cddb373a97ac92cdd
    pull_policy: ${pull_policy}
    container_name: ${jellyseerr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - radarr
      - sonarr
    init: true
    network_mode: "service:gluetunmediarr"
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=5055
    volumes:
      - jellyseerr-config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  radarr:
    image: lscr.io/linuxserver/radarr:latest@sha256:c984533510abe0219a70e80d15bd0d212b7df21baa0913759c4ce6cc9092240b
    pull_policy: ${pull_policy}
    container_name: ${radarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - radarr-config:/config
      - media_downloads:/media_downloads
      - media_movies:/movies

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:4b8a853b76337cd5de5f69961e23b7d0792ce7bf0a8be083dd7202ef670bfc34
    pull_policy: ${pull_policy}
    container_name: ${sonarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SONARR__SERVER__PORT=${sonarr_port_ui}
    volumes:
      - sonarr-config:/config
      - media_downloads:/media_downloads
      - media_tvshows:/tv

  sonarr2:
    image: lscr.io/linuxserver/sonarr:latest@sha256:4b8a853b76337cd5de5f69961e23b7d0792ce7bf0a8be083dd7202ef670bfc34
    pull_policy: ${pull_policy}
    container_name: ${sonarr2_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SONARR__SERVER__PORT=${sonarr2_port_ui}
    volumes:
      - sonarr2-config:/config
      - media_downloads:/media_downloads
      - media_anime:/anime

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest@sha256:1d49ebdfaae525d9e1e4ad5b7fa1753e364da44ac1b5e6acae241a2173ac09a4
    pull_policy: ${pull_policy}
    container_name: ${lidarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - lidarr-config:/config
      - media_downloads:/media_downloads
      - media_music:/music

  notifiarr:
    image: golift/notifiarr:latest@sha256:4180afa7df046312ac1dd08574a9fd23eae0d2828c126f0113314a6b5643cc82
    pull_policy: ${pull_policy}
    container_name: ${notifiarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    volumes:
      - notifiarr-config:/config
      - /var/run/utmp:/var/run/utmp:ro
      - /etc/machine-id:/etc/machine-id:ro