---
include:
  - ../components/caddy_network.yaml

#networks:

volumes:
  gluetun-config:
    external: true
  qbittorrent-config:
    external: true
  sabnzbd-config:
    external: true
  prowlarr-config:
    external: true
  jellyseerr-config:
    external: true
  radarr-config:
    external: true
  sonarr-config:
    external: true
  sonarr2-config:
    external: true
  lidarr-config:
    external: true
  notifiarr-config:
    external: true

  media_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/downloads"
  media_downloads_torrents:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/downloads/torrents"
  media_downloads_usenet:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/downloads/usenet"
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"
  media_music:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/music"
  media_anime:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/anime"

#secrets:

services:
  gluetunmediarr:
    image: qmcgaw/gluetun:latest@sha256:e3c42d634cfd781639f6b87ed3e606b67dc5d27b90fe5fb8c607d9dc7b4ed63f
    pull_policy: ${pull_policy}
    container_name: ${gluetunmediarr_container_name}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.200
    ports:
      - ${qbittorrent_port_ui}:${qbittorrent_port_ui}
      - ${sabnzbd_port_ui}:${sabnzbd_port_ui}
      - ${flaresolverr_port}:${flaresolverr_port}
      - ${prowlarr_port_ui}:${prowlarr_port_ui}
      - ${jellyseerr_port_ui}:${jellyseerr_port_ui}
      - ${radarr_port_ui}:${radarr_port_ui}
      - ${sonarr_port_ui}:${sonarr_port_ui}
      - ${lidarr_port_ui}:${lidarr_port_ui}
      - ${notifiarr_port_ui}:${notifiarr_port_ui}
      - ${sonarr_port_ui}:${sonarr_port_ui}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - GLUETUN_HTTP_CONTROL_SERVER_ENABLE=on
      #- WIREGUARD_ENDPOINT_IP=${MEDIARR_WG_ENDPOINT_IP}
      #- WIREGUARD_ENDPOINT_PORT=${MEDIARR_WG_ENDPOINT_PORT}
      #- WIREGUARD_PUBLIC_KEY=${MEDIARR_WG_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${MEDIARR_WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${MEDIARR_WG_ADDRESSES}
      - SERVER_HOSTNAMES=${MEDIARR_WG_SERVER_HOSTNAME}
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${qbittorrent_port_ui}/api/v2/app/setPreferences 2>&1'
      - DOT=on
      - DOT_PROVIDERS=cloudflare,google,quad9
      - DOT_CACHING=on
      - BLOCK_MALICIOUS=off
      - BLOCK_ADS=off
      - BLOCK_SURVEILLANCE=off
      - DNS_KEEP_NAMESERVER=off
      - DNS_ADDRESS=127.0.0.1
    volumes:
      - gluetun-config:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:b8a08ffba8850e2e71153e153cf5eed2dedbf499ef9b123262735ce924b65586
    pull_policy: ${pull_policy}
    container_name: ${qbittorrent_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=${qbittorrent_port_ui}
    volumes:
      - qbittorrent-config:/config
      - media_downloads_torrents:/media_downloads/torrents

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest@sha256:fba727f777f6b2633fcdeaea94abc85d73148f2a6b19a8158907bdd5b6e145d0
    pull_policy: ${pull_policy}
    container_name: ${sabnzbd_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - sabnzbd-config:/config
      - media_downloads_usenet:/media_downloads/usenet

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    pull_policy: ${pull_policy}
    container_name: ${flaresolverr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest@sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884
    pull_policy: ${pull_policy}
    container_name: ${prowlarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - flaresolverr
      - qbittorrent
      - sabnzbd
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - prowlarr-config:/config

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest@sha256:9cc9e9ee6cd5cf5a23feb45c37742ba34cfd6314d81d259cddb373a97ac92cdd
    pull_policy: ${pull_policy}
    container_name: ${jellyseerr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - radarr
      - sonarr
    init: true
    network_mode: "service:gluetunmediarr"
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=5055
    volumes:
      - jellyseerr-config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  radarr:
    image: lscr.io/linuxserver/radarr:latest@sha256:270f25698624b57b86ca119cc95399d7ff15be8297095b4e1223fd5b549b732c
    pull_policy: ${pull_policy}
    container_name: ${radarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - radarr-config:/config
      - media_downloads:/media_downloads
      - media_movies:/movies

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca
    pull_policy: ${pull_policy}
    container_name: ${sonarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SONARR__SERVER__PORT=${sonarr_port_ui}
    volumes:
      - sonarr-config:/config
      - media_downloads:/media_downloads
      - media_tvshows:/tv

  sonarr2:
    image: lscr.io/linuxserver/sonarr:latest@sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca
    pull_policy: ${pull_policy}
    container_name: ${sonarr2_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SONARR__SERVER__PORT=${sonarr2_port_ui}
    volumes:
      - sonarr2-config:/config
      - media_downloads:/media_downloads
      - media_anime:/anime

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest@sha256:be65454ba890ad01a93b01cfc178adfa1a397b487bfdce2ac23bd956c473d10d
    pull_policy: ${pull_policy}
    container_name: ${lidarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
      - prowlarr
    network_mode: "service:gluetunmediarr"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - lidarr-config:/config
      - media_downloads:/media_downloads
      - media_music:/music

  notifiarr:
    image: golift/notifiarr:latest@sha256:4180afa7df046312ac1dd08574a9fd23eae0d2828c126f0113314a6b5643cc82
    pull_policy: ${pull_policy}
    container_name: ${notifiarr_container_name}
    restart: ${restart}
    depends_on:
      - gluetunmediarr
    network_mode: "service:gluetunmediarr"
    volumes:
      - notifiarr-config:/config
      - /var/run/utmp:/var/run/utmp:ro
      - /etc/machine-id:/etc/machine-id:ro
