---
networks:
  caddy:
    name: caddy-network

volumes:
  open-webui:
#secrets:

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest@sha256:53a4d2fc8c7a7cc620cd18e6fe416ed9940f2db87fddf837e3aa55111bec6995 #https://github.com/open-webui/open-webui/pkgs/container/open-webui/526750706?tag=latest
    pull_policy: ${pull_policy}
    container_name: ${openwebui_container_name}
    restart: ${restart}
    networks:
      - caddy
    ports:
      - "${openwebui_port_8080}:8080"
    environment: 
      - 'OLLAMA_BASE_URL=https://ollama.zacarrie.com'
    volumes:
      - /docker/openwebui/data:/app/backend/data
