---
include:
  - ../components/caddy_network.yaml

#networks:

volumes:
  vikunja-config:
    external: true
  vikunja-db:
    external: true

#secrets:

services:
  vikunja:
    image: vikunja/vikunja@sha256:874c871ced75d1bf5783c8ff56c31a758fdf4343183ecd6ab9c7be0bc83e7d99
    pull_policy: ${pull_policy}
    container_name: ${vikunja_container_name}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.60
    ports:
      - ${vikunja_port_3456}:3456
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.${CADDY_PRIVATE_DOMAIN}
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_SECRET}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SECRET}
    volumes:
      - vikunja-config:/app/vikunja/files
    depends_on:
      vikunja-db:
        condition: service_healthy

  vikunja-db:
    image: postgres:18@sha256:5773fe724c49c42a7a9ca70202e11e1dff21fb7235b335a73f39297d200b73a2
    pull_policy: ${pull_policy}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.65
    environment:
      POSTGRES_PASSWORD: ${VIKUNJA_SECRET}
      POSTGRES_USER: vikunja
    volumes:
      - vikunja-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s