---
#networks:

#volumes:

#secrets:

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable@sha256:4041ad318224500cf9513c513b1bb927d9dd252f63bbd3d11c92006c1172c86c
    pull_policy: ${pull_policy}
    container_name: ${frigate_container_name}
    restart: ${restart}
    privileged: true
    stop_grace_period: 30s
    shm_size: "4gb"
    network_mode: host
    #ports:
    #  - "${frigate_container_port8971}:8971"
    #  - "${frigate_container_port5000}:5000"
    #  - "${frigate_container_port1984}:1984" 
    #  - "${frigate_container_port8554}:8554" # RTSP feeds
    #  - "${frigate_container_port8555}:8555/tcp" # WebRTC over tcp
    #  - "${frigate_container_port8555}:8555/udp" # WebRTC over udp 
    environment: 
      - LIBVA_DRIVER_NAME=radeonsi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config:/config
      - /docker/frigate/recording:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 


